### ISSUE TITLE
Since version 1.16 program stop working correctly

### ISSUE THREAD

**Issue by AlfredBauer** [moisesmcardona/rav1e_gui#17]
Since version 1.16 (In 1.15 all seems to be okay) program doesn't work normal.
No matter how I change settings the output file still the same, with low video bitrate(~115kb).
I was changing speed, quantizer and so on but output result the same.

**Comment by moisespr123** [comment]
Hi,

There are currently some issues with the latest versions of rav1e. You can try to go to "Advanced Options" and change Tile/Rows to 0, or 2/1, as reported by users in the [AV1 Discord server](https://discord.gg/7dFwjyG).

Also, there are issues running rav1e on CPUs with the AVX2 instruction set. This is why in v1.16 I added the option to run rav1e under WSL since the issue is not present in the Linux version.

Once these issues are addressed, I'll keep updating the software periodically.

-Moisés
