### ISSUE TITLE
Make it more obvious that temp file path is required

### ISSUE THREAD

**Issue by linearray** [moisesmcardona/rav1e_gui#5]
When you do not enter a temp file path you just get the exception `System.ArgumentException: The path is not of a legal form.`

I almost didn't figure it out and thought there is something wrong with the input file path. Maybe it's best to just use `System.IO.Path.GetTempPath()` if the user doesn't enter anything?

**Comment by moisespr123** [comment]
Totally forgot about checking the input, output and temporary fields. It has been fixed in the latest commits.

I'd prefer the user specifies another folder other than the system temporary files as that way it doesn't possibly mess with other temporary files in that folder.

The user will now receive a message telling him to browse for a temporary path
